package com.nerdginger.projectmate.core.sort

/**
 * Fractional indexing: order-preserving string keys with no renumbering.
 *
 * Anything the user can drag — cards in a column, statuses, checklist entries —
 * is ordered by one of these. Moving an item means minting a key strictly
 * between its new neighbours and writing **one row**, rather than rewriting the
 * whole column.
 *
 * A `Double` position is the usual shortcut and quietly fails: repeatedly
 * inserting between the same two items halves the gap each time and exhausts
 * IEEE-754 precision after roughly fifty moves, at which point items start
 * sharing a position. Strings have no such floor. See docs/DECISIONS.md D-009.
 *
 * Keys sort with plain lexicographic (byte) comparison, which is what SQLite's
 * default BINARY collation does, so `ORDER BY sortKey` needs no custom collator.
 *
 * ## Format
 *
 * A key is an integer part followed by an optional fractional part. The integer
 * part's first character encodes its own length, so keys stay short while
 * appending — `a0`, `a1`, … `az`, `b00`, … — instead of growing one character
 * per append. The fractional part subdivides between two adjacent integers and
 * never ends in `'0'` (a trailing zero would give two distinct spellings of the
 * same position).
 *
 * This is the well-known fractional-indexing scheme; the implementation follows
 * the reference algorithm closely because its edge cases are easy to get subtly
 * wrong and hard to notice.
 */
object SortKey {

    /**
     * Base-62 digits in ASCII order, so digit order and byte order agree.
     * `'0'..'9'` (48–57) < `'A'..'Z'` (65–90) < `'a'..'z'` (97–122).
     */
    private const val DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

    /** The lowest representable integer part. Nothing may sort before it. */
    private const val SMALLEST_INTEGER = "A00000000000000000000000000"

    /** The integer part handed out when a list is empty. */
    const val FIRST: String = "a0"

    /**
     * A key strictly between [before] and [after].
     *
     * Pass `null` for an open end: `between(null, first)` prepends,
     * `between(last, null)` appends, and `between(null, null)` returns [FIRST].
     *
     * @throws IllegalArgumentException if [before] >= [after], or if either key
     *   is malformed.
     */
    fun between(before: String?, after: String?): String {
        before?.let(::validate)
        after?.let(::validate)
        require(before == null || after == null || before < after) {
            "before must sort before after, got before=$before after=$after"
        }

        if (before == null) {
            if (after == null) return FIRST

            val integerPart = integerPartOf(after)
            val fraction = after.substring(integerPart.length)

            // Already at the floor — the only room left is below the fraction.
            if (integerPart == SMALLEST_INTEGER) return integerPart + midpoint("", fraction)

            // `after` has a fractional part, so its integer part alone sorts before it.
            if (integerPart < after) return integerPart

            return requireNotNull(decrementInteger(integerPart)) {
                "run out of room below $after"
            }
        }

        if (after == null) {
            val integerPart = integerPartOf(before)
            val fraction = before.substring(integerPart.length)
            // If the integer part can't be incremented, subdivide above the fraction.
            return incrementInteger(integerPart) ?: (integerPart + midpoint(fraction, null))
        }

        val beforeInteger = integerPartOf(before)
        val beforeFraction = before.substring(beforeInteger.length)
        val afterInteger = integerPartOf(after)
        val afterFraction = after.substring(afterInteger.length)

        if (beforeInteger == afterInteger) {
            return beforeInteger + midpoint(beforeFraction, afterFraction)
        }

        val next = requireNotNull(incrementInteger(beforeInteger)) { "run out of room above $before" }
        // If the next whole integer already fits in the gap, it's the shortest answer.
        return if (next < after) next else beforeInteger + midpoint(beforeFraction, null)
    }

    /**
     * [count] keys in ascending order, all strictly between [before] and [after].
     *
     * Generated by repeated subdivision rather than [count] independent calls,
     * so the results are correctly ordered relative to each other.
     */
    fun sequence(before: String?, after: String?, count: Int): List<String> {
        require(count >= 0) { "count must not be negative" }
        if (count == 0) return emptyList()
        if (count == 1) return listOf(between(before, after))

        // Bisect so keys stay short: place the middle key, then fill both halves.
        val middle = count / 2
        val middleKey = between(before, after)
        return sequence(before, middleKey, middle) +
            middleKey +
            sequence(middleKey, after, count - middle - 1)
    }

    /** Convenience for appending to the end of an existing ordered list. */
    fun append(last: String?): String = between(last, null)

    fun isValid(key: String): Boolean =
        runCatching { validate(key) }.isSuccess

    // ---------------------------------------------------------------- internals

    /**
     * A string strictly between the two fractional parts, both of which are
     * digits-only with no trailing `'0'`. [after] of `null` means "unbounded".
     */
    private fun midpoint(before: String, after: String?): String {
        if (after != null) {
            require(before < after) { "midpoint requires before < after" }
        }
        require(!before.endsWith('0')) { "fraction must not end in a zero digit: $before" }
        require(after == null || !after.endsWith('0')) { "fraction must not end in a zero digit: $after" }

        if (after != null) {
            // Copy the shared prefix through, then subdivide what differs.
            var shared = 0
            while (true) {
                val b = before.getOrNull(shared) ?: '0'
                val a = after.getOrNull(shared)
                if (a == null || b != a) break
                shared++
            }
            if (shared > 0) {
                return after.substring(0, shared) + midpoint(before.drop(shared), after.drop(shared))
            }
        }

        val lowDigit = if (before.isNotEmpty()) DIGITS.indexOf(before[0]) else 0
        val highDigit = if (after != null && after.isNotEmpty()) DIGITS.indexOf(after[0]) else DIGITS.length

        if (highDigit - lowDigit > 1) {
            // There is a spare digit between them; take the middle one.
            return DIGITS[Math.round(0.5 * (lowDigit + highDigit)).toInt()].toString()
        }

        // The leading digits are adjacent, so we must go deeper.
        return if (after != null && after.length > 1) {
            after.substring(0, 1)
        } else {
            DIGITS[lowDigit] + midpoint(before.drop(1), null)
        }
    }

    /**
     * How many characters the integer part occupies, encoded in its first
     * character. `'a'` means 2, `'b'` means 3, and so on; the uppercase half
     * mirrors this downwards for integers below zero.
     */
    private fun integerLengthOf(head: Char): Int = when (head) {
        in 'a'..'z' -> head - 'a' + 2
        in 'A'..'Z' -> 'Z' - head + 2
        else -> throw IllegalArgumentException("invalid integer-part header: '$head'")
    }

    private fun integerPartOf(key: String): String {
        require(key.isNotEmpty()) { "key must not be empty" }
        val length = integerLengthOf(key[0])
        require(length <= key.length) { "key is shorter than its integer part declares: $key" }
        return key.substring(0, length)
    }

    private fun validate(key: String) {
        require(key.isNotEmpty()) { "key must not be empty" }
        require(key != SMALLEST_INTEGER) { "$SMALLEST_INTEGER is reserved as the lower bound" }
        val integerPart = integerPartOf(key)
        integerPart.forEach {
            require(DIGITS.contains(it)) { "key contains a non-base-62 character: $key" }
        }
        val fraction = key.substring(integerPart.length)
        fraction.forEach {
            require(DIGITS.contains(it)) { "key contains a non-base-62 character: $key" }
        }
        require(!fraction.endsWith('0')) { "fractional part must not end in a zero digit: $key" }
    }

    /** The next whole integer part, or `null` at the ceiling. */
    private fun incrementInteger(integerPart: String): String? {
        val head = integerPart[0]
        val digits = integerPart.drop(1).toCharArray()

        var carry = true
        var i = digits.lastIndex
        while (carry && i >= 0) {
            val next = DIGITS.indexOf(digits[i]) + 1
            if (next == DIGITS.length) {
                digits[i] = '0'
            } else {
                digits[i] = DIGITS[next]
                carry = false
            }
            i--
        }

        if (!carry) return head + String(digits)

        // Overflowed: widen the integer part by moving to the next header.
        return when (head) {
            'Z' -> "a0"
            'z' -> null
            else -> {
                val nextHead = head + 1
                // Crossing into the lowercase half lengthens the part; within
                // the uppercase half it shortens.
                if (nextHead > 'a') nextHead + String(digits) + "0" else nextHead + String(digits.dropLast(1).toCharArray())
            }
        }
    }

    /** The previous whole integer part, or `null` at the floor. */
    private fun decrementInteger(integerPart: String): String? {
        val head = integerPart[0]
        val digits = integerPart.drop(1).toCharArray()

        var borrow = true
        var i = digits.lastIndex
        while (borrow && i >= 0) {
            val next = DIGITS.indexOf(digits[i]) - 1
            if (next == -1) {
                digits[i] = DIGITS.last()
            } else {
                digits[i] = DIGITS[next]
                borrow = false
            }
            i--
        }

        if (!borrow) return head + String(digits)

        return when (head) {
            'a' -> "Z" + DIGITS.last()
            'A' -> null
            else -> {
                val prevHead = head - 1
                if (prevHead < 'Z') prevHead + String(digits) + DIGITS.last() else prevHead + String(digits.dropLast(1).toCharArray())
            }
        }
    }
}
